export const PREFETCH_MAP: Record<string, string[]> = {
  "/": ["/api/dashboard-stats", "/api/accounts"],
  "/calendar": ["/api/reservations", "/api/apartments"],
  "/reservations": ["/api/reservations", "/api/apartments"],
  "/podnajem": ["/api/subleases", "/api/apartments"],
  "/customers": ["/api/customers"],
  "/apartments": ["/api/apartments", "/api/owners"],
  "/owners": ["/api/owners"],
  "/saldo-firmowe": ["/api/accounts", "/api/dashboard-stats"],
  "/v2/przychody": ["/api/reservations", "/api/apartments"],
  "/v2/koszty": ["/api/costs", "/api/apartments"],
  "/salda": ["/api/salda"],
  "/import-bankowy": ["/api/bank-statements"],
  "/dokumenty-ksiegowe": ["/api/invoices"],
  "/contracts-services": ["/api/service-contracts"],
  "/sprawy-sadowe": ["/api/legal-cases"],
  "/rcp/admin": ["/api/rcp/admin/dashboard"],
  "/pracownicy": ["/api/employees"],
  "/occupancy": ["/api/reservations", "/api/apartments"],
  "/profitability": ["/api/reservations", "/api/apartments"],
  "/ustawienia": ["/api/company-settings"],
  "/bank-connections": ["/api/gocardless/connections"],
};
